### ISSUE TITLE
component.rb 24 line

### ISSUE THREAD

**Issue by shenyefeng** [cloudfoundry/vcap-common#17]
if space name contains Chinese, then varz.bytesize.to_s returns a wrong value. so download the varz file error.

**Comment by Quintaminant** [comment]
Hi @shenyefeng 

While attempting to recreate this error, we created spaces and apps with Chinese characters in the name. When queried on varz endpoints, they were reported without problem and no errors appeared in the VM logs. It is possible that we don't fully understand what action you are taking that results in a problem -- would you be willing to clarify your workflow that is leading you to this error state?

Best wishes,
@DanLavine && @Quintaminant, CF Runtime Team

**Comment by shenyefeng** [comment]
wget http://64ba4dd500cbxxxxxx2d03615e809:14f179b8a48xxxxx845d4fe9cc97fd@192.168.1.28:60576/varz
return file contains 
![contains](https://cloud.githubusercontent.com/assets/6102871/8222182/528d7c4e-159a-11e5-8b8e-9a1f204ad964.png)

then the file not download completely

![end](https://cloud.githubusercontent.com/assets/6102871/8222208/86732fa4-159a-11e5-9841-a7da544485da.jpg)

**Comment by shenyefeng** [comment]
We modified the code from 
[200, { 'Content-Type' => 'application/json', 'Content-Length' => varz.length.to_s }, varz]
to 
[200, { 'Content-Type' => 'application/json' }, varz]
it worked.
